apiVersion: v1
kind: Namespace
metadata:
  name: who2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: who2
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
        ports:
          - name: web
            containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: who2
  name: whoami
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    name: web
  selector:
    app: whoami